/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kodeProgram;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author ROG ZEPHYRUS M16
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    // public static String userName;
    // public static String password;

    public MainLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameLog = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        PasswordLog = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        loginText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butLogin = new javax.swing.JButton();
        butReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(102, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 640));

        UsernameLog.setBackground(new java.awt.Color(255, 255, 255));
        UsernameLog.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USERNAME :");

        userText.setBorder(null);
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UsernameLogLayout = new javax.swing.GroupLayout(UsernameLog);
        UsernameLog.setLayout(UsernameLogLayout);
        UsernameLogLayout.setHorizontalGroup(
                UsernameLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UsernameLogLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        UsernameLogLayout.setVerticalGroup(
                UsernameLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UsernameLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userText, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        PasswordLog.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD :");

        passText.setBorder(null);
        passText.setCaretColor(new java.awt.Color(255, 255, 255));
        passText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PasswordLogLayout = new javax.swing.GroupLayout(PasswordLog);
        PasswordLog.setLayout(PasswordLogLayout);
        PasswordLogLayout.setHorizontalGroup(
                PasswordLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PasswordLogLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passText)));
        PasswordLogLayout.setVerticalGroup(
                PasswordLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PasswordLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        loginText.setEditable(false);
        loginText.setBackground(new java.awt.Color(0, 204, 204));
        loginText.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        loginText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginText.setText("LOGIN");
        loginText.setToolTipText("");
        loginText.setBorder(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tokoIcon.png"))); // NOI18N

        butLogin.setText("LOGIN");
        butLogin.setBorder(null);
        butLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butLoginMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                butLoginMouseExited(evt);
            }
        });
        butLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLoginActionPerformed(evt);
            }
        });

        butReg.setText("REGISTER");
        butReg.setBorder(null);
        butReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butRegMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                butRegMouseExited(evt);
            }
        });
        butReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(UsernameLog, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(PasswordLog, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(butReg, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(loginText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(UsernameLog, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PasswordLog, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(butLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(butReg, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(232, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_butLoginActionPerformed
        // TODO add your handling code here:

        if (userText.getText().isEmpty() || passText.getText().isEmpty()) {
            userText.setText("Masukkan Username");
            userText.setForeground(new Color(255, 102, 102));
            passText.setText("Masukkan Password");
            passText.setEchoChar((char) 0);
            passText.setForeground(new Color(255, 102, 102));

            String nama = userText.getText();
            String pass = passText.getText();

        } else {
            HalamanUtama item1 = new HalamanUtama();
            this.setVisible(false);
            item1.setVisible(true);
        }
    }// GEN-LAST:event_butLoginActionPerformed

    private void butRegActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_butRegActionPerformed
        // TODO add your handling code here:
        Registrasi regis = new Registrasi();
        this.setVisible(false);
        regis.setVisible(true);
    }// GEN-LAST:event_butRegActionPerformed

    private void butRegMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_butRegMouseEntered
        // TODO add your handling code here:
        butReg.setBackground(new Color(102, 102, 102));
    }// GEN-LAST:event_butRegMouseEntered

    private void butRegMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_butRegMouseExited
        // TODO add your handling code here:
        butReg.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_butRegMouseExited

    private void butLoginMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_butLoginMouseEntered
        // TODO add your handling code here:
        butLogin.setBackground(new Color(102, 102, 102));
    }// GEN-LAST:event_butLoginMouseEntered

    private void butLoginMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_butLoginMouseExited
        // TODO add your handling code here:
        butLogin.setBackground(new Color(255, 255, 255));
    }// GEN-LAST:event_butLoginMouseExited

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_userTextMouseClicked
        // TODO add your handling code here:
        userText.setForeground(new Color(0, 0, 0));
        userText.setText("");
    }// GEN-LAST:event_userTextMouseClicked

    private void passTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_passTextMouseClicked
        // TODO add your handling code here:
        passText.setForeground(new Color(0, 0, 0));
        passText.setText("");
        passText.setEchoChar('*');
    }// GEN-LAST:event_passTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PasswordLog;
    private javax.swing.JPanel UsernameLog;
    private javax.swing.JButton butLogin;
    private javax.swing.JButton butReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginText;
    private javax.swing.JPasswordField passText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
